---
title: "CV"
author: "Andrew Collin Stewart"
email: andrew.c.stewart@gmail.com
output:
  pdf_document:
    latex_engine: pdflatex
    template: templates/svm-latex-cv.tex
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
geometry: margin=1in
# jobtitle: test
keywords: R Markdown, academic CV, template
linkcolor: blue
fontawesome: yes
phone: +202 505 3633
address: San Francisco · California
updated: no
urlcolor: blue
web: andrewcstewart.com
github: andrewcstewart
bibliography: references.bib
nocite: "@*"
---

# SUMMARY

Data scientist with a strong background in applied research and development in big data, machine learning, and statistics.  Passionate about improving business processes through sound experimental design and analysis.

# PROFESSIONAL EXPERIENCE

**Twist Bioscience**, Scientist (Bioinformatics) \hfill 2015-2018

 * Developed predictive models to optimize manufacturing processes involving cell colony picking and misassembly.  Desgin and analysis of experiments for improving chemical manufacturing processes.  Architect behind data analytics culture centered around data warehouse and ETL processes.

**Veracyte**, Scientist (R&D Data Analysis Team) \hfill 2014-2015

 * Developed high dimensional machine learning models for classification in cancer diagnostics using a combination of supervised and semisupervised techinques.
 
**Smithsonian Institution**, Data Science Specialist (Office of the CIO) \hfill 2013-2014

 * Provided analytical support on research projects in population genetics, phylogenmoics, and metagenomics.  Developed ensemble machine learning approach for classification of signatures of natural selection in genetic populations using support vector machines.
 
**Keygene**, Bioinformatician (Applied Systems Biology) \hfill 2009-2012
 
 * Performed data mining and data visualization of gene regulatory networks using gene weighted correlation network analysis, R and graph visualizations.  Performed exploratory data mining on hyperspectral imaging of field crop plots using dimensionality reduction techniques and 3D data visualization. Performed modeling and simulation of plant architecture using Lindenmayer systems.

**Navy Medical Research Center**, Research Assistant (Biodefense Research Directorate) \hfill 2006-2009

 * Applied Hidden Markov Models, clustering algorithms towards rapid identification of pathogens from genomic sequencing data.  Designed and built data analytics system for collection, processing and analysis of microbial genomic data using perl, R, SQL, and HPC systems.
 
# EDUCATION EXPERIENCE

**Johns Hopkins University**, M.S. Computer Science \hfill 2015

**University of Maryland College Park**, B.S. Biology \hfill 2006

# TECHNICAL SKILLS

|              |                                                         |
|-------------:|---------------------------------------------------------|
| **Expertise** | Data Analysis, Analytics & Dashboards, Predictive Modeling, Research & Development, ETL, Big Data Queries, Data Mining, Machine Learning, AI
| **Programming** | R, Python, Rust, C/C++, Java, Docker , AWS |
| **Data Analysis** | tidyverse, ggplot2, pandas, numpy, scipy, scikit-learn, Shiny, Tableau, Spark
| **Machine Learning** | classification, regression, clustering, feature engineering |
| **Statistics** | bayesian inference, multilevel modeling, hypothesis testing, power analysis, dimensionality reduction |

# TEACHING EXPERIENCE

**Johns Hopkins University**, Graduate Teaching Assistant \hfill 2016-2017

* Spring 2017: 605.448.81 - Data Science
* Spring 2017: 605.445.81 - Artificial Intelligence
* Fall 2016: 605.448.81 - Data Science
* Fall 2016: 605.448.82 - Data Science

# VOLUNTEER EXPERIENCE

**Voteocracy**, Data Science Volunteer \hfill 2016

 * Applied network analysis techniques to identify marketing targets from Twitter data.

**Bayes Impact**, Data Science Intern \hfill 2015

 * Developed multiclass predictive model of criminal activity based on geographic and census data.

# PUBLICATIONS
